import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { createClient } from '@supabase/supabase-js';
import { Check, ChevronLeft, CircleAlert, ClipboardList, FileDown, FolderKanban, LogOut, Menu, Plus, Save, Send, ShieldCheck, UserRound, X } from 'lucide-react';
import './styles.css';

const url = import.meta.env.VITE_SUPABASE_URL;
const key = import.meta.env.VITE_SUPABASE_ANON_KEY;
const supabase = url && key ? createClient(url, key) : null;
const today = () => new Date().toISOString().slice(0, 10);
const blankReport = () => ({ report_date: today(), completed_work: '', in_progress: '', issues: '', actions: '', tomorrow_plan: '', status: 'draft', attachments: [] });
const demoReports = [{ id: 'demo-1', report_date: today(), completed_work: '고객 제안서 초안 작성\n주간 회의 참석', in_progress: '신규 기능 테스트', issues: '테스트 계정 권한 확인 필요', actions: '관리자에게 권한 요청', tomorrow_plan: '제안서 검토 반영', status: 'submitted', profiles: { full_name: '김민지' } }];
const labels = { completed_work: '오늘 한 일', in_progress: '진행 업무', issues: '문제점', actions: '조치 내용', tomorrow_plan: '내일 할 일' };

function App() {
  const [session, setSession] = useState(null); const [profile, setProfile] = useState(null); const [view, setView] = useState('home');
  const [reports, setReports] = useState([]); const [projects, setProjects] = useState([]); const [report, setReport] = useState(blankReport());
  const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false); const demo = !supabase;
  const role = profile?.role || 'employee';
  const flash = (message) => { setNotice(message); setTimeout(() => setNotice(''), 3500); };
  useEffect(() => { if (!supabase) { setProfile({ full_name: '김민지', role: 'employee' }); setReports(demoReports); return; }
    supabase.auth.getSession().then(({ data }) => setSession(data.session)); const { data: l } = supabase.auth.onAuthStateChange((_e, s) => setSession(s)); return () => l.subscription.unsubscribe(); }, []);
  useEffect(() => { if (session) loadData(); }, [session]);
  async function loadData() { const uid = session.user.id; const { data: p } = await supabase.from('profiles').select('*').eq('id', uid).single(); setProfile(p);
    const reportsQuery = p?.role === 'admin' ? supabase.from('daily_reports').select('*, profiles(full_name)').order('report_date', { ascending: false }) : supabase.from('daily_reports').select('*, profiles(full_name)').eq('user_id', uid).order('report_date', { ascending: false });
    const [{ data: r }, { data: pr }] = await Promise.all([reportsQuery, supabase.from('projects').select('*, profiles(full_name)').order('updated_at', { ascending: false })]); setReports(r || []); setProjects(pr || []); }
  async function login(email, password) { const { error } = await supabase.auth.signInWithPassword({ email, password }); if (error) flash(error.message); }
  async function saveReport(status = 'draft') { if (!demo && !session) return; setBusy(true); const payload = { ...report, status, user_id: session?.user.id, submitted_at: status === 'submitted' ? new Date().toISOString() : null };
    if (demo) { const saved = { ...payload, id: report.id || crypto.randomUUID(), profiles: { full_name: profile.full_name } }; setReports(x => [saved, ...x.filter(a => a.id !== saved.id)]); setReport(saved); flash(status === 'submitted' ? '보고서를 제출했습니다.' : '임시 저장했습니다.'); }
    else { const { data, error } = report.id ? await supabase.from('daily_reports').update(payload).eq('id', report.id).select().single() : await supabase.from('daily_reports').insert(payload).select().single(); if (error) flash(error.message); else { setReport(data); flash(status === 'submitted' ? '보고서를 제출했습니다.' : '임시 저장했습니다.'); loadData(); } } setBusy(false); }
  async function uploadFiles(e) { const files = Array.from(e.target.files || []); if (!files.length) return; if (demo) { setReport(r => ({ ...r, attachments: [...(r.attachments || []), ...files.map(f => ({ name: f.name, url: '#' }))] })); return; }
    setBusy(true); const added=[]; for (const file of files) { const path = `${session.user.id}/${Date.now()}-${file.name}`; const { error } = await supabase.storage.from('report-files').upload(path, file); if (!error) { const { data } = supabase.storage.from('report-files').getPublicUrl(path); added.push({ name: file.name, path, url: data.publicUrl }); } } setReport(r => ({ ...r, attachments: [...(r.attachments || []), ...added] })); setBusy(false); }
  async function review(item, status) { const comment = status === 'revision_requested' ? prompt('보완 요청 내용을 입력하세요.') : ''; if (status === 'revision_requested' && comment === null) return; const { error } = await supabase.from('daily_reports').update({ status, manager_comment: comment || null, reviewed_at: new Date().toISOString(), reviewed_by: session.user.id }).eq('id', item.id); if (error) flash(error.message); else { flash(status === 'approved' ? '승인했습니다.' : '보완을 요청했습니다.'); loadData(); } }
  function exportPdf(item) { const content = Object.entries(labels).map(([k, label]) => `<section><h3>${label}</h3><p>${(item[k] || '-').replaceAll('\n','<br/>')}</p></section>`).join(''); const win = window.open('', '_blank'); win.document.write(`<html><head><meta charset="utf-8"><title>일일업무보고서</title><style>body{font-family:Malgun Gothic,Arial;padding:28px;color:#172033}h1{font-size:23px}h2{font-size:16px;color:#506078}section{border-top:1px solid #ddd;padding:10px 0}h3{font-size:14px;margin:0 0 6px}p{line-height:1.6;margin:0;white-space:normal}@media print{body{padding:0}}</style></head><body><h1>일일 업무 보고서</h1><h2>${item.report_date} · ${item.profiles?.full_name || profile?.full_name || ''}</h2>${content}<script>window.onload=()=>window.print()<\/script></body></html>`); win.document.close(); }
  if (supabase && !session) return <Login onLogin={login} />;
  const submitted = reports.filter(r => r.status === 'submitted').length; const approved = reports.filter(r => r.status === 'approved').length;
  return <main className="app">{notice && <div className="toast">{notice}</div>}<header><div><span className="eyebrow">DAILY FLOW</span><h1>{view === 'editor' ? '업무 보고 작성' : view === 'projects' ? '주요 프로젝트' : role === 'admin' ? '관리자 대시보드' : '나의 업무'}</h1></div><button className="avatar" onClick={() => supabase ? supabase.auth.signOut() : flash('데모 모드입니다.')}>{profile?.full_name?.slice(0,1) || '나'}</button></header>
  {demo && <div className="demo">데모 모드 · Supabase 환경변수를 설정하면 실제 데이터가 저장됩니다.</div>}
  {view === 'home' && <><section className="welcome"><p>안녕하세요, <b>{profile?.full_name}</b>님</p><span>{today().replaceAll('-','.')} 업무를 기록해 보세요.</span></section><section className="stats"><div><b>{reports.length}</b><span>전체 보고</span></div><div><b>{submitted}</b><span>검토 대기</span></div><div><b>{approved}</b><span>승인 완료</span></div></section>{role === 'admin' ? <AdminList reports={reports} onReview={review} onPdf={exportPdf} /> : <><button className="primary full" onClick={() => { setReport(blankReport()); setView('editor'); }}><Plus size={19}/> 오늘 업무 보고 작성</button><ReportList reports={reports} onOpen={x => { setReport(x); setView('editor'); }} onPdf={exportPdf}/></>}</>}
  {view === 'editor' && <ReportEditor report={report} setReport={setReport} onBack={() => setView('home')} onSave={saveReport} onUpload={uploadFiles} busy={busy} />}
  {view === 'projects' && <Projects projects={projects} role={role} session={session} demo={demo} profile={profile} refresh={loadData} flash={flash}/>}<nav><button className={view==='home'?'active':''} onClick={()=>setView('home')}><ClipboardList size={21}/><span>업무보고</span></button><button className={view==='projects'?'active':''} onClick={()=>setView('projects')}><FolderKanban size={21}/><span>프로젝트</span></button><button onClick={()=>supabase ? supabase.auth.signOut() : flash('데모 모드입니다.')}><UserRound size={21}/><span>내 정보</span></button></nav></main>;
}
function Login({ onLogin }) { const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); return <main className="login"><div className="logo"><ClipboardList size={32}/></div><span className="eyebrow">DAILY FLOW</span><h1>매일의 업무를<br/>깔끔하게 기록하세요.</h1><form onSubmit={e=>{e.preventDefault();onLogin(email,password)}}><label>이메일<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>비밀번호<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button className="primary full">로그인</button></form></main> }
function ReportList({ reports,onOpen,onPdf }) { return <section className="list"><div className="section-title"><h2>최근 보고서</h2></div>{reports.length ? reports.map(r=><article className="card" key={r.id} onClick={()=>onOpen(r)}><div><b>{r.report_date}</b><p>{r.completed_work || '작성 내용 없음'}</p></div><Status status={r.status}/><button className="icon" onClick={e=>{e.stopPropagation();onPdf(r)}} aria-label="PDF 저장"><FileDown size={18}/></button></article>) : <div className="empty">아직 작성한 보고서가 없습니다.</div>}</section> }
function AdminList({reports,onReview,onPdf}) { return <section className="list"><div className="section-title"><h2>검토할 보고서</h2><span>{reports.filter(r=>r.status==='submitted').length}건</span></div>{reports.map(r=><article className="admin-card" key={r.id}><div className="card-head"><div><b>{r.profiles?.full_name || '직원'} · {r.report_date}</b><p>{r.completed_work || '내용 없음'}</p></div><Status status={r.status}/></div>{r.status==='submitted' && <div className="actions"><button onClick={()=>onReview(r,'revision_requested')} className="secondary">보완 요청</button><button onClick={()=>onReview(r,'approved')} className="approve"><Check size={16}/> 승인</button></div>}<button className="pdf-link" onClick={()=>onPdf(r)}><FileDown size={15}/> PDF 저장</button></article>)}</section> }
function ReportEditor({report,setReport,onBack,onSave,onUpload,busy}) { return <><button className="back" onClick={onBack}><ChevronLeft size={20}/> 목록으로</button><div className="date-row"><label>보고일<input type="date" value={report.report_date} onChange={e=>setReport({...report,report_date:e.target.value})}/></label><Status status={report.status}/></div><section className="form">{Object.entries(labels).map(([key,label])=><label key={key}>{label}<textarea value={report[key] || ''} placeholder={`${label}을 입력하세요`} onChange={e=>setReport({...report,[key]:e.target.value})}/></label>)}<label className="upload">사진·파일 첨부<input type="file" multiple accept="image/*,.pdf,.doc,.docx,.xls,.xlsx" onChange={onUpload}/><span><Plus size={18}/> 파일 선택</span></label>{report.attachments?.map((a,i)=><a className="file" target="_blank" key={i} href={a.url}>{a.name}</a>)}{report.manager_comment && <div className="comment"><CircleAlert size={19}/><div><b>관리자 보완 요청</b><p>{report.manager_comment}</p></div></div>}</section><div className="sticky-actions"><button className="secondary" disabled={busy} onClick={()=>onSave('draft')}><Save size={18}/> 임시저장</button><button className="primary" disabled={busy} onClick={()=>onSave('submitted')}><Send size={18}/> 제출하기</button></div></> }
function Projects({projects,role,session,demo,profile,refresh,flash}) { const [adding,setAdding]=useState(false); const [p,setP]=useState({name:'', progress:0, details:''}); async function save() { if(!p.name) return; if(demo) { flash('데모에서는 화면만 확인할 수 있습니다.'); setAdding(false); return; } const {error}=await supabase.from('projects').insert({...p,owner_id:session.user.id}); if(error) flash(error.message); else {setAdding(false);setP({name:'',progress:0,details:''});refresh();} } return <><button className="primary full" onClick={()=>setAdding(!adding)}><Plus size={19}/> 주요 프로젝트 추가</button>{adding&&<section className="project-form"><input placeholder="프로젝트명" value={p.name} onChange={e=>setP({...p,name:e.target.value})}/><label>진행률 {p.progress}%<input type="range" value={p.progress} onChange={e=>setP({...p,progress:+e.target.value})}/></label><textarea placeholder="진행 현황 및 추진 사항" value={p.details} onChange={e=>setP({...p,details:e.target.value})}/><button className="primary full" onClick={save}>저장</button></section>}<section className="list"><h2>진행 중인 프로젝트</h2>{projects.length?projects.map(x=><article className="project card" key={x.id}><div className="project-top"><b>{x.name}</b><span>{x.progress}%</span></div><div className="bar"><i style={{width:`${x.progress}%`}}/></div><p>{x.details || '추진 사항이 없습니다.'}</p></article>):<div className="empty">등록된 주요 프로젝트가 없습니다.</div>}</section></> }
function Status({status}) { const map={draft:'임시저장',submitted:'검토 대기',approved:'승인 완료',revision_requested:'보완 요청'}; return <span className={`status ${status}`}>{map[status]||status}</span> }
createRoot(document.getElementById('root')).render(<App/>);
